    tableanalyze_img:
        build: ./docker/build/
        ports:
            - "80:80"
            - "3000:3000"
            - "4000:4000"
            - "3306:3306"
        volumes:
        - ./src/frontend:/root/frontend
        - ./src/frontend/build:/var/www/html
        - ./src/backend:/root/backend
        - ./docker/build/install:/root/install
        - ./docker/build/conf/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
        container_name: tableanalyze_ctn






